version: "3.5"
networks:
  escola_lms:
    name: escola_lms
    driver: bridge
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    networks:
      - escola_lms   
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
      - TZ=Europe/Warsaw

