on: push
name: Generate TypeScript Models definitions from Eloquent
jobs:
  generate:
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:8-work

    services:
      mysql:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Instantiate package
        run: apt-get install git -y

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Copy environment configuration files
        run: |
          cp .env.ci.mysql .env

      - name: Install composer dependencies
        run: |
          apt-get -y install git
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          php artisan key:generate
          php artisan migrate:fresh
          php artisan passport:keys --force
          php artisan passport:client --personal --no-interaction

      - name: Generate TypeScript
        run: php artisan config:cache && php artisan typescript:generate

      - name: Install deps
        run: npm i

      - name: Test definitions before anything
        run: npm run test

      - name: Generate typedoc
        run: npm run doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build

      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          add: "models.d.ts"
